# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categorys',
            new_name='category',
        ),
    ]
