# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(null='True')),
                ('about', models.TextField(max_length=100, null='True')),
            ],
        ),
    ]
