# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(null='True')),
                ('quantity', models.IntegerField(null='True')),
                ('about', models.TextField(max_length=100, null='True')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapp.Products')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
