# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0005_auto_20180705_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
