# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0008_auto_20180709_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='about',
            field=models.CharField(default='NEW', max_length=100, null=True),
        ),
    ]
