# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0011_auto_20180709_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=100, null=True)),
                ('l', models.CharField(max_length=100, null=True)),
                ('e', models.EmailField(max_length=254, null=True)),
                ('p', models.IntegerField(null=True)),
                ('a', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
