# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0012_ord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='about',
        ),
    ]
