# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0014_cart_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='about',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
