# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0017_auto_20181220_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
